'use client';

import { useRef } from 'react';
import { motion, useScroll, useTransform, useInView } from 'framer-motion';

const energyTerms = [
  {
    symbol: 'Q_solar',
    label: 'Solar Flux',
    value: '1,361 W/m²',
    desc: 'Direct solar irradiance at 1 AU. Computed for actual orbit geometry, shadow periods, and panel orientation.',
    formula: 'αₛ · Aₚ · S · cos(θ)',
  },
  {
    symbol: 'Q_albedo',
    label: 'Earth Albedo',
    value: '0.30 avg',
    desc: 'Reflected solar energy from Earth surface. Varies with latitude, cloud cover, and surface type.',
    formula: 'αₛ · a · S · F_earth · Aₚ',
  },
  {
    symbol: 'Q_IR',
    label: 'Earth IR',
    value: '237 W/m²',
    desc: 'Infrared radiation emitted by Earth. Temperature-dependent, computed per orbital position.',
    formula: 'ε · σ · T⁴_earth · F_earth · Aₚ',
  },
  {
    symbol: 'Q_int',
    label: 'Internal Dissipation',
    value: 'Per component',
    desc: 'Heat generated by electronics, batteries, payloads. Time-varying power profiles per operational mode.',
    formula: 'Σ P_component(t)',
  },
];

function EquationDisplay() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: '-100px' });

  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0 }}
      animate={isInView ? { opacity: 1 } : {}}
      transition={{ duration: 1 }}
      className="py-16"
    >
      {/* The master equation */}
      <div className="text-center mb-4">
        <span className="data-label">ENERGY BALANCE EQUATION</span>
      </div>
      <div
        className="font-mono text-lg md:text-2xl lg:text-3xl text-center py-8 leading-relaxed"
        style={{ color: 'var(--tc-text)' }}
      >
        <motion.span
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ delay: 0.2, duration: 0.5 }}
        >
          <span className="text-accent">Q</span>
          <sub className="text-xs" style={{ color: 'var(--tc-text-muted)' }}>solar</sub>
        </motion.span>
        <span className="mx-2" style={{ color: 'var(--tc-text-dim)' }}>+</span>
        <motion.span
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ delay: 0.35, duration: 0.5 }}
        >
          <span className="text-accent">Q</span>
          <sub className="text-xs" style={{ color: 'var(--tc-text-muted)' }}>albedo</sub>
        </motion.span>
        <span className="mx-2" style={{ color: 'var(--tc-text-dim)' }}>+</span>
        <motion.span
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ delay: 0.5, duration: 0.5 }}
        >
          <span className="text-accent">Q</span>
          <sub className="text-xs" style={{ color: 'var(--tc-text-muted)' }}>IR</sub>
        </motion.span>
        <span className="mx-2" style={{ color: 'var(--tc-text-dim)' }}>+</span>
        <motion.span
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ delay: 0.65, duration: 0.5 }}
        >
          <span className="text-accent">Q</span>
          <sub className="text-xs" style={{ color: 'var(--tc-text-muted)' }}>int</sub>
        </motion.span>
        <span className="mx-4" style={{ color: 'var(--tc-text-dim)' }}>=</span>
        <motion.span
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ delay: 0.8, duration: 0.5 }}
        >
          <span style={{ color: 'var(--tc-text)' }}>εσT</span>
          <sup className="text-sm">4</sup>
        </motion.span>
        <span className="mx-2" style={{ color: 'var(--tc-text-dim)' }}>+</span>
        <motion.span
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ delay: 0.95, duration: 0.5 }}
        >
          <span style={{ color: 'var(--tc-text)' }}>mc</span>
          <span style={{ color: 'var(--tc-text-muted)' }}>(</span>
          <span style={{ color: 'var(--tc-text)' }}>dT/dt</span>
          <span style={{ color: 'var(--tc-text-muted)' }}>)</span>
        </motion.span>
      </div>
      <div className="rule-accent mx-auto max-w-xl" />
    </motion.div>
  );
}

export function EnergyBalanceSection() {
  const sectionRef = useRef<HTMLElement>(null);
  const { scrollYProgress } = useScroll({
    target: sectionRef,
    offset: ['start end', 'end start'],
  });

  const bgY = useTransform(scrollYProgress, [0, 1], [60, -60]);

  return (
    <section
      id="analysis"
      ref={sectionRef}
      className="relative py-24 lg:py-32 px-6 lg:px-10 overflow-hidden"
    >
      {/* Parallax grid behind */}
      <motion.div
        style={{ y: bgY }}
        className="absolute inset-0 eng-grid pointer-events-none opacity-50"
        aria-hidden
      />

      {/* Scroll-linked orbital arc + satellite + sun bloom */}

      <div className="relative z-10 max-w-[1400px] mx-auto">
        {/* Section header — left-aligned */}
        <div className="mb-6">
          <span className="data-label">SECTION 01</span>
        </div>
        <h2 className="font-mono font-bold text-display-lg tracking-tight max-w-3xl" style={{ color: 'var(--tc-text)' }}>
          The physics your hardware
          <br />
          <span className="text-accent">demands</span>
        </h2>
        <p
          className="mt-4 max-w-xl text-base leading-relaxed font-sans"
          style={{ color: 'var(--tc-text-secondary)' }}
        >
          Every spacecraft thermal analysis comes down to one equation. We solve it 
          with engineering-grade numerical methods — transient and steady-state — 
          for every node in your thermal network.
        </p>

        {/* Equation display */}
        <EquationDisplay />

        {/* Energy terms grid — asymmetric layout */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-px mt-8" style={{ backgroundColor: 'var(--tc-border)' }}>
          {energyTerms.map((term, i) => (
            <motion.div
              key={term.symbol}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: '-80px' }}
              transition={{ delay: i * 0.1, duration: 0.5 }}
              className="p-8 relative group"
              style={{ backgroundColor: 'var(--tc-surface)' }}
            >
              {/* Term number */}
              <div className="flex items-baseline justify-between mb-4">
                <span className="data-label">{term.symbol.toUpperCase()}</span>
                <span className="font-mono text-xs tabular-nums" style={{ color: 'var(--tc-text-muted)' }}>
                  {String(i + 1).padStart(2, '0')}
                </span>
              </div>

              <h3 className="font-mono text-lg font-semibold mb-1" style={{ color: 'var(--tc-text)' }}>
                {term.label}
              </h3>
              <div className="font-mono text-sm mb-3 text-accent">
                {term.value}
              </div>
              <p className="text-sm leading-relaxed font-sans" style={{ color: 'var(--tc-text-secondary)' }}>
                {term.desc}
              </p>

              {/* Formula */}
              <div
                className="mt-4 pt-4 font-mono text-xs"
                style={{ borderTop: '1px solid var(--tc-border)', color: 'var(--tc-text-muted)' }}
              >
                <span className="text-accent opacity-60">▸</span> {term.formula}
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
