/**
 * Seed script: Populates the materials database with ~50 common spacecraft thermal materials.
 * Values sourced from NASA GSFC Thermal Engineering Handbook, ESA ECSS standards,
 * and published spacecraft thermal control literature.
 *
 * Run with: npx tsx src/scripts/seed-materials.ts
 */

import 'dotenv/config';
import { neon } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-http';
import { materials } from '../lib/db/schema';

interface MaterialSeed {
  name: string;
  category: 'metal' | 'composite' | 'mli' | 'paint' | 'osr' | 'adhesive';
  absorptivity: number; // α_s (solar)
  emissivity: number; // ε_IR
  conductivity: number; // W/(m·K)
  specificHeat: number; // J/(kg·K)
  density: number; // kg/m³
  tempRangeMin: number; // K
  tempRangeMax: number; // K
}

const MATERIALS: MaterialSeed[] = [
  // ── Metals ───────────────────────────────────────────────────────────────
  {
    name: 'Aluminum 6061-T6',
    category: 'metal',
    absorptivity: 0.379,
    emissivity: 0.04,
    conductivity: 167,
    specificHeat: 896,
    density: 2700,
    tempRangeMin: 20,
    tempRangeMax: 450,
  },
  {
    name: 'Aluminum 7075-T6',
    category: 'metal',
    absorptivity: 0.379,
    emissivity: 0.04,
    conductivity: 130,
    specificHeat: 960,
    density: 2810,
    tempRangeMin: 20,
    tempRangeMax: 450,
  },
  {
    name: 'Titanium Ti-6Al-4V',
    category: 'metal',
    absorptivity: 0.52,
    emissivity: 0.12,
    conductivity: 6.7,
    specificHeat: 526,
    density: 4430,
    tempRangeMin: 20,
    tempRangeMax: 600,
  },
  {
    name: 'Stainless Steel 304',
    category: 'metal',
    absorptivity: 0.42,
    emissivity: 0.11,
    conductivity: 16.2,
    specificHeat: 500,
    density: 8000,
    tempRangeMin: 20,
    tempRangeMax: 800,
  },
  {
    name: 'Stainless Steel 316L',
    category: 'metal',
    absorptivity: 0.42,
    emissivity: 0.11,
    conductivity: 16.3,
    specificHeat: 500,
    density: 7990,
    tempRangeMin: 20,
    tempRangeMax: 800,
  },
  {
    name: 'Invar 36',
    category: 'metal',
    absorptivity: 0.50,
    emissivity: 0.10,
    conductivity: 13.4,
    specificHeat: 515,
    density: 8050,
    tempRangeMin: 20,
    tempRangeMax: 500,
  },
  {
    name: 'Copper C101 (OFHC)',
    category: 'metal',
    absorptivity: 0.30,
    emissivity: 0.03,
    conductivity: 391,
    specificHeat: 385,
    density: 8940,
    tempRangeMin: 20,
    tempRangeMax: 400,
  },
  {
    name: 'Beryllium',
    category: 'metal',
    absorptivity: 0.40,
    emissivity: 0.10,
    conductivity: 200,
    specificHeat: 1825,
    density: 1850,
    tempRangeMin: 20,
    tempRangeMax: 500,
  },
  {
    name: 'Magnesium AZ31B',
    category: 'metal',
    absorptivity: 0.38,
    emissivity: 0.07,
    conductivity: 96,
    specificHeat: 1024,
    density: 1770,
    tempRangeMin: 20,
    tempRangeMax: 350,
  },
  {
    name: 'Kovar (Fe-Ni-Co)',
    category: 'metal',
    absorptivity: 0.50,
    emissivity: 0.10,
    conductivity: 17.3,
    specificHeat: 439,
    density: 8360,
    tempRangeMin: 20,
    tempRangeMax: 500,
  },
  {
    name: 'Inconel 718',
    category: 'metal',
    absorptivity: 0.55,
    emissivity: 0.14,
    conductivity: 11.4,
    specificHeat: 435,
    density: 8190,
    tempRangeMin: 20,
    tempRangeMax: 700,
  },
  {
    name: 'Molybdenum',
    category: 'metal',
    absorptivity: 0.44,
    emissivity: 0.06,
    conductivity: 138,
    specificHeat: 251,
    density: 10220,
    tempRangeMin: 20,
    tempRangeMax: 1000,
  },

  // ── Composites ──────────────────────────────────────────────────────────
  {
    name: 'CFRP (Quasi-Isotropic)',
    category: 'composite',
    absorptivity: 0.92,
    emissivity: 0.85,
    conductivity: 5.0,
    specificHeat: 900,
    density: 1600,
    tempRangeMin: 80,
    tempRangeMax: 400,
  },
  {
    name: 'CFRP (Unidirectional, along fiber)',
    category: 'composite',
    absorptivity: 0.92,
    emissivity: 0.85,
    conductivity: 120,
    specificHeat: 900,
    density: 1600,
    tempRangeMin: 80,
    tempRangeMax: 400,
  },
  {
    name: 'GFRP (Glass Fiber Reinforced Polymer)',
    category: 'composite',
    absorptivity: 0.50,
    emissivity: 0.80,
    conductivity: 0.3,
    specificHeat: 900,
    density: 2000,
    tempRangeMin: 80,
    tempRangeMax: 400,
  },
  {
    name: 'Kevlar/Epoxy',
    category: 'composite',
    absorptivity: 0.55,
    emissivity: 0.85,
    conductivity: 0.04,
    specificHeat: 1400,
    density: 1380,
    tempRangeMin: 80,
    tempRangeMax: 380,
  },
  {
    name: 'Aluminum Honeycomb Core',
    category: 'composite',
    absorptivity: 0.379,
    emissivity: 0.04,
    conductivity: 2.5,
    specificHeat: 896,
    density: 130,
    tempRangeMin: 20,
    tempRangeMax: 450,
  },
  {
    name: 'CFRP Honeycomb Core',
    category: 'composite',
    absorptivity: 0.92,
    emissivity: 0.85,
    conductivity: 0.8,
    specificHeat: 900,
    density: 80,
    tempRangeMin: 80,
    tempRangeMax: 400,
  },

  // ── MLI Blankets ────────────────────────────────────────────────────────
  {
    name: 'MLI 10-Layer (Aluminized Mylar)',
    category: 'mli',
    absorptivity: 0.14,
    emissivity: 0.03,
    conductivity: 0.001,
    specificHeat: 1090,
    density: 40,
    tempRangeMin: 20,
    tempRangeMax: 400,
  },
  {
    name: 'MLI 15-Layer (Aluminized Mylar)',
    category: 'mli',
    absorptivity: 0.14,
    emissivity: 0.02,
    conductivity: 0.0007,
    specificHeat: 1090,
    density: 55,
    tempRangeMin: 20,
    tempRangeMax: 400,
  },
  {
    name: 'MLI 20-Layer (Aluminized Mylar)',
    category: 'mli',
    absorptivity: 0.14,
    emissivity: 0.015,
    conductivity: 0.0005,
    specificHeat: 1090,
    density: 70,
    tempRangeMin: 20,
    tempRangeMax: 400,
  },
  {
    name: 'Single-Layer Aluminized Kapton (1 mil)',
    category: 'mli',
    absorptivity: 0.38,
    emissivity: 0.67,
    conductivity: 0.12,
    specificHeat: 1090,
    density: 1420,
    tempRangeMin: 20,
    tempRangeMax: 670,
  },
  {
    name: 'Single-Layer Aluminized Mylar (0.5 mil)',
    category: 'mli',
    absorptivity: 0.14,
    emissivity: 0.04,
    conductivity: 0.15,
    specificHeat: 1360,
    density: 1390,
    tempRangeMin: 20,
    tempRangeMax: 420,
  },
  {
    name: 'Beta Cloth (Teflon-coated fiberglass)',
    category: 'mli',
    absorptivity: 0.24,
    emissivity: 0.90,
    conductivity: 0.26,
    specificHeat: 750,
    density: 460,
    tempRangeMin: 80,
    tempRangeMax: 540,
  },

  // ── Paints/Coatings ────────────────────────────────────────────────────
  {
    name: 'Aeroglaze Z306 (Black, Polyurethane)',
    category: 'paint',
    absorptivity: 0.95,
    emissivity: 0.91,
    conductivity: 0.20,
    specificHeat: 1500,
    density: 1200,
    tempRangeMin: 80,
    tempRangeMax: 400,
  },
  {
    name: 'Aeroglaze Z307 (Black, Electrically Conductive)',
    category: 'paint',
    absorptivity: 0.97,
    emissivity: 0.91,
    conductivity: 0.20,
    specificHeat: 1500,
    density: 1300,
    tempRangeMin: 80,
    tempRangeMax: 400,
  },
  {
    name: 'Aeroglaze A276 (White, Polyurethane)',
    category: 'paint',
    absorptivity: 0.26,
    emissivity: 0.88,
    conductivity: 0.20,
    specificHeat: 1500,
    density: 1300,
    tempRangeMin: 80,
    tempRangeMax: 400,
  },
  {
    name: 'MAP PUK (White Paint)',
    category: 'paint',
    absorptivity: 0.25,
    emissivity: 0.91,
    conductivity: 0.20,
    specificHeat: 1500,
    density: 1250,
    tempRangeMin: 80,
    tempRangeMax: 400,
  },
  {
    name: 'Chemglaze A971 (Black, Silicone)',
    category: 'paint',
    absorptivity: 0.96,
    emissivity: 0.87,
    conductivity: 0.20,
    specificHeat: 1500,
    density: 1200,
    tempRangeMin: 100,
    tempRangeMax: 500,
  },
  {
    name: 'ITO Coating (Indium Tin Oxide)',
    category: 'paint',
    absorptivity: 0.45,
    emissivity: 0.12,
    conductivity: 10,
    specificHeat: 340,
    density: 7140,
    tempRangeMin: 20,
    tempRangeMax: 600,
  },
  {
    name: 'Alodine (Chromate Conversion on Al)',
    category: 'paint',
    absorptivity: 0.41,
    emissivity: 0.15,
    conductivity: 167,
    specificHeat: 896,
    density: 2700,
    tempRangeMin: 20,
    tempRangeMax: 400,
  },
  {
    name: 'Black Anodized Aluminum',
    category: 'paint',
    absorptivity: 0.86,
    emissivity: 0.86,
    conductivity: 167,
    specificHeat: 896,
    density: 2700,
    tempRangeMin: 20,
    tempRangeMax: 400,
  },
  {
    name: 'Clear Anodized Aluminum',
    category: 'paint',
    absorptivity: 0.35,
    emissivity: 0.84,
    conductivity: 167,
    specificHeat: 896,
    density: 2700,
    tempRangeMin: 20,
    tempRangeMax: 400,
  },
  {
    name: 'Gold Coating (Vacuum Deposited)',
    category: 'paint',
    absorptivity: 0.25,
    emissivity: 0.03,
    conductivity: 317,
    specificHeat: 129,
    density: 19300,
    tempRangeMin: 20,
    tempRangeMax: 800,
  },
  {
    name: 'Silver Teflon (FEP)',
    category: 'paint',
    absorptivity: 0.08,
    emissivity: 0.78,
    conductivity: 0.25,
    specificHeat: 1170,
    density: 2150,
    tempRangeMin: 80,
    tempRangeMax: 475,
  },
  {
    name: 'Germanium Black Kapton',
    category: 'paint',
    absorptivity: 0.51,
    emissivity: 0.73,
    conductivity: 0.12,
    specificHeat: 1090,
    density: 1420,
    tempRangeMin: 80,
    tempRangeMax: 400,
  },

  // ── Optical Solar Reflectors (OSR) ──────────────────────────────────────
  {
    name: 'OSR Silvered Teflon (5 mil FEP)',
    category: 'osr',
    absorptivity: 0.08,
    emissivity: 0.78,
    conductivity: 0.25,
    specificHeat: 1170,
    density: 2150,
    tempRangeMin: 80,
    tempRangeMax: 475,
  },
  {
    name: 'OSR Aluminized Teflon (5 mil FEP)',
    category: 'osr',
    absorptivity: 0.15,
    emissivity: 0.78,
    conductivity: 0.25,
    specificHeat: 1170,
    density: 2150,
    tempRangeMin: 80,
    tempRangeMax: 475,
  },
  {
    name: 'Second-Surface Mirror (Glass)',
    category: 'osr',
    absorptivity: 0.07,
    emissivity: 0.82,
    conductivity: 1.0,
    specificHeat: 840,
    density: 2500,
    tempRangeMin: 80,
    tempRangeMax: 500,
  },
  {
    name: 'Silvered Quartz Mirror',
    category: 'osr',
    absorptivity: 0.07,
    emissivity: 0.80,
    conductivity: 1.4,
    specificHeat: 740,
    density: 2200,
    tempRangeMin: 80,
    tempRangeMax: 600,
  },
  {
    name: 'Z-93 White Paint',
    category: 'osr',
    absorptivity: 0.16,
    emissivity: 0.92,
    conductivity: 0.20,
    specificHeat: 1500,
    density: 1250,
    tempRangeMin: 80,
    tempRangeMax: 400,
  },
  {
    name: 'S13G/LO-1 White Paint',
    category: 'osr',
    absorptivity: 0.20,
    emissivity: 0.90,
    conductivity: 0.20,
    specificHeat: 1500,
    density: 1300,
    tempRangeMin: 80,
    tempRangeMax: 400,
  },

  // ── Adhesives ───────────────────────────────────────────────────────────
  {
    name: 'EA 9394 (Epoxy Paste Adhesive)',
    category: 'adhesive',
    absorptivity: 0.50,
    emissivity: 0.85,
    conductivity: 0.35,
    specificHeat: 1100,
    density: 1500,
    tempRangeMin: 80,
    tempRangeMax: 450,
  },
  {
    name: 'Hysol EA 956 (Epoxy Film Adhesive)',
    category: 'adhesive',
    absorptivity: 0.50,
    emissivity: 0.85,
    conductivity: 0.30,
    specificHeat: 1100,
    density: 1200,
    tempRangeMin: 80,
    tempRangeMax: 420,
  },
  {
    name: 'RTV 566 (Silicone Adhesive)',
    category: 'adhesive',
    absorptivity: 0.45,
    emissivity: 0.90,
    conductivity: 0.27,
    specificHeat: 1260,
    density: 1100,
    tempRangeMin: 80,
    tempRangeMax: 530,
  },
  {
    name: 'Cho-Therm 1671 (Thermally Conductive Gap Filler)',
    category: 'adhesive',
    absorptivity: 0.50,
    emissivity: 0.85,
    conductivity: 1.6,
    specificHeat: 1200,
    density: 2700,
    tempRangeMin: 80,
    tempRangeMax: 470,
  },
];

async function seed(): Promise<void> {
  const url = process.env.DATABASE_URL;
  if (!url) {
    console.error('DATABASE_URL is not set. Copy .env.example to .env and configure.');
    process.exit(1);
  }

  const sql = neon(url);
  const seedDb = drizzle(sql);

  console.log(`Seeding ${MATERIALS.length} materials...`);

  for (const mat of MATERIALS) {
    await seedDb.insert(materials).values({
      name: mat.name,
      category: mat.category,
      absorptivity: mat.absorptivity,
      emissivity: mat.emissivity,
      conductivity: mat.conductivity,
      specificHeat: mat.specificHeat,
      density: mat.density,
      tempRangeMin: mat.tempRangeMin,
      tempRangeMax: mat.tempRangeMax,
      isDefault: true,
      userId: null,
      projectId: null,
    });
    console.log(`  ✓ ${mat.name}`);
  }

  console.log(`\nDone! Seeded ${MATERIALS.length} materials.`);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
